name: Dist

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dist:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          ref: dist

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x
    
      - name: Build dist
        run: |
          mkdir dist
          deno run -A build.ts
      
      - name: Push dist
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git branch
          git checkout dist
          git add dist
          git commit -m "Dist: ${{ github.event.commits[0].message }}" || true
          git push origin dist
